version: 0.2

# env:
#   variables:
#     CODEBUILD_RESOLVED_SOURCE_VERSION: "1.0"

phases:
  install:
    runtime-versions:
      "nodejs:18-alpine"

  pre_build:
    commands:
      - npm i ./package.json
  build:
    commands:
      - docker build -f Dockerfile.notification -t 851725252478.dkr.ecr.us-east-1.amazonaws.com/repo-notification.123/notification:latest .
      - docker build -f Dockerfile.email -t 851725252478.dkr.ecr.us-east-1.amazonaws.com/repo-notification.123/email:latest .
     # - docker tag 851725252478.dkr.ecr.us-east-1.amazonaws.com/repo-notification.123:latest 851725252478.dkr.ecr.us-east-1.amazonaws.com/repo-notification.123:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      #- docker push 851725252478.dkr.ecr.us-east-1.amazonaws.com/repo-notification.123:latest
      #- docker push 851725252478.dkr.ecr.us-east-1.amazonaws.com/repo-notification.123:$CODEBUILD_RESOLVED_SOURCE_VERSION

